server:
  compression:
    enabled: true
  port: 9001
  http2:
    enabled: true

spring:
  application:
    name: bom-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/bom_db
    username: bom_user
    password: DEV2020
  jackson:
    default-property-inclusion: non_null
  task:
    execution:
      pool:
        core-size: 8
        max-size: 20
        queue-capacity: 200
      shutdown:
        await-termination: true
        await-termination-period: 60

management:
  endpoint:
    health:
      show-details: when_authorized
    caches:
      enabled: true
  endpoints:
    web:
      exposure:
        include: cache, health, info
  health:
    defaults:
      enabled: true
  info:
    defaults:
      enabled: true

logging:
  level:
    root: info

bom:
  cors:
    allowed-headers: "*"
    allowed-origins: "*"
  security:
    jwt:
      secret-key: super-secret
