CREATE USER bom_admin WITH PASSWORD 'DEV2020' LOGIN;
CREATE USER bom_user WITH PASSWORD 'DEV2020' LOGIN;

CREATE DATABASE bom_db OWNER bom_admin;

REVOKE CONNECT ON DATABASE bom_db FROM PUBLIC;
GRANT CONNECT ON DATABASE bom_db TO bom_user;
